table D_Clientes
	lineageTag: 3abec13e-b976-4916-a910-24f1f7abb1b9

	column Cod_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 25c4ece9-0899-43ca-94af-1e18a0191e93
		summarizeBy: none
		sourceColumn: Cod_Cliente

		annotation SummarizationSetBy = Automatic

	column Nome_Cliente
		dataType: string
		lineageTag: 266bd8a7-b19f-4f94-baf6-02e6d426ca72
		summarizeBy: none
		sourceColumn: Nome_Cliente

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Cod_uf
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ebf9b601-ac8e-4140-8fda-930db632f2c5
		summarizeBy: none
		sourceColumn: Cod_uf

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition D_Clientes-c46a10e3-84e3-49c9-a266-34eff4214555 = m
		mode: import
		queryGroup: Dimensao
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("D:\EAD\Power BI 3\Fontes\Vendas\Dimensoes\D_CLIENTES.xlsx"), null, true),
				    D_Clientes_Sheet = Fonte{[Item="D_Clientes",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(D_Clientes_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Cod_Cliente", Int64.Type}, {"Nome_Cliente", type text}, {"Cod_uf", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

